FROM node:20-alpine

WORKDIR /app

COPY ./backend/package.json ./package.json
RUN npm install

COPY ./backend ./

ARG SUPABASE_DIRECT_URL
ARG SUPABASE_ANON_KEY
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

EXPOSE 3000

CMD ["node", "index.js"]