name: Deploy the frontend

on:
  push:
    branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: shrutiiiyet/pixelvai-frontend:${{ github.sha }}
      - name: Deploy to the VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 700 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@154.26.134.104 -t "
          docker stop pixelvai-frontend || true &&
          docker rm pixelvai-frontend || true
          docker run -d \
          --name pixelvai-frontend \
          -p 5173:80 \
          shrutiiiyet/pixelvai-frontend:${{ github.sha }}
          "
          
